### ISSUE TITLE
[Index pages & About pages] space above h1

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag-redesign#21]
For Understanding and Techniques index and about pages, add space above the H1

Here's the CSS from [About Supplemental Guidance](https://www.w3.org/WAI/WCAG2/supplemental/about/)
```
}
h1, h1+h2 {
    margin-top: 0;
}
h1 {
    line-height: 1.2;
    font-weight: 400;
}
h1 {
    font-size: 24px;
    font-size: 1.5rem;
}
h1, h2, h3, h4 {
    color: #005a6a;
    color: var(--wai-green);
}
h1, h2 {
    margin: 60px 0 20px;
}
h1, h2, h3, h4, h5, h6 {
    padding: 0;
}

```

**Comment by michael-n-cooper** [comment]
While I can put the above CSS into the local CSS, it is better to load whatever WAI CSS you want to load that includes that. I need the URI to that.

**Comment by SteveALee** [comment]
I think this should be bottom margin of nav above

**Comment by SteveALee** [comment]
fixed in #27

**Comment by shawna-slh** [comment]
Hey @SteveALee 

I'm still getting h1 squished up against the pager:
![image](https://user-images.githubusercontent.com/6991814/186742486-ac649574-aee9-46c4-b844-0c42d6e5adee.png)

@1:30pmCT
In Vivaldi and in FireFox

**Comment by shawna-slh** [comment]
Steve, I moved this to Milestone Level 4, since seems it's not so easy afterall :-/

**Comment by SteveALee** [comment]
Will check its notvanything silly/obvious as bowser specific behaviour  is uncommon these days.

**Comment by shawna-slh** [comment]
Hey @SteveALee after discussion with EOWG, I am proposing (for confirmation once folks see it implemented) not having a page bar at all for techniques. In mocking up that PR, I used this CSS: https://github.com/w3c/wcag-redesign/pull/33/files#diff-f6c1bcf8a240e8ffed6045cdf73c3b8917515902d26a525fc881fea16dbb63ca

Thoughts?

**Comment by shawna-slh** [comment]
looks like works on the All Techniques / index page, so I'm closing this issue
![image](https://user-images.githubusercontent.com/6991814/190836196-5876d448-c575-4b1e-9df0-0113d526c9b7.png)
